version: "3.8"

services:
  server:
    build:
      context: ../.
      dockerfile: build/packages/Dockerfile
      args:
        - GO_VERSION=1.20
        - ADAPTER=http/fiber
      network: "host"
    environment:
      - ENV=dev
      - PORT=3000
      - REPOSITORY_ADAPTER=redis
      - MEMCACHED_URL=memcached:11211
      - REDIS_URL=redis:6379
    volumes:
      - ../.:/usr/app/
    ports:
      - "3000:3000"

  memcached:
    image: memcached
    ports:
      - "11211:11211"

  redis:
    image: redis
    ports:
      - "6379:6379"
